name: Auto Suite (CI/CD + PR Review + Issue Processing + Docs)

on:
  push:
    branches: [ "main" ]            # CI/CD & Docs
  pull_request:
    types: [opened, reopened, synchronize]  # CI/CD & PR Review
    branches: [ "main" ]
  issues:
    types: [opened, assigned]       # Issue Processing

# デフォルト権限は最小限（必要なジョブで個別に上書き）
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ------------------------------------------------------------
  # 1) CI/CD: プッシュ/PRごとのビルド・テスト
  # ------------------------------------------------------------
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        if: hashFiles('requirements.txt') != ''
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          if command -v pytest >/dev/null 2>&1; then
            pytest
          else
            echo "pytest not found, skipping tests."
          fi

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            tests/reports
            .pytest_cache
          if-no-files-found: ignore

  # ------------------------------------------------------------
  # 2) PR Review Automation: PRにAIコメント（Claude）
  # ------------------------------------------------------------
  ai_pr_review:
    name: AI PR Review (Claude)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    # PRへコメント/レビューを書けるように権限付与
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun runtime
        uses: oven-sh/setup-bun@v2

      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 例）必要に応じて追加の入力を設定
          # mode: "review"
          # review_scope: "diff"

  # ------------------------------------------------------------
  # 3) Issue Processing Automation: Issueの自動トリアージ
  # ------------------------------------------------------------
  ai_issue_triage:
    name: AI Issue Triage (Claude)
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun runtime
        uses: oven-sh/setup-bun@v2

      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 例）自動ラベル/返信テンプレの指定など
          # mode: "issue-triage"

  # ------------------------------------------------------------
  # 4) Documentation Generation: コード変更に合わせてDocs生成/更新
  # ------------------------------------------------------------
  generate_docs:
    name: Generate & Commit Docs
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write   # 生成ドキュメントのコミット・プッシュに必要
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        if: hashFiles('mcp-server/requirements.txt') != ''
        run: pip install -r mcp-server/requirements.txt

      - name: Run Doc Generator
        run: |
          if [ -f "mcp-server/scripts/generate_docs.py" ]; then
            python mcp-server/scripts/generate_docs.py
          else
            echo "No doc generator found. Skipping."
          fi

      - name: Commit Documentation
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            generated_contexts/*.md
            docs/**/*
          message: "docs: 自動生成されたドキュメントを更新 [skip ci]"
          push: true